### ISSUE TITLE
Add plots of fits compared to calibration and evaluation data in `eval_post_process` for every location-forecast date

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/wastewater-informed-covid-forecasting#165]
## Goal
Make it easy to look at data the models were fit to and evaluated against, so that we can investigate easily individual forecast dates-locations. 

# Tasks 
- [ ] saved image (png) of hospital admissions calibration + evaluation data with fits (median, 50th, 95th percentiles) in nested folder structure along with `input_hosp_data`
- [ ] saved image (png) of site level wastewater concentrations from calibration + evaluation data with fits in nested folder structure along with `input_ww_data`
- [ ] Adding to this the daily growth rate comparison plots described in https://github.com/cdcent/cfa-forecast-renewal-ww/issues/771
